# Generated by Django 3.2.4 on 2021-06-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicalrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('martial', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('dateofbirth', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('disease', models.TextField()),
                ('medicine', models.CharField(max_length=50)),
                ('allergies', models.CharField(max_length=50)),
                ('tobacco', models.CharField(max_length=50)),
                ('drugs', models.CharField(max_length=50)),
                ('alchohol', models.CharField(max_length=50)),
                ('generalhealth', models.IntegerField()),
            ],
        ),
    ]
